MOUSE_BUTTON = '<Button>'
MOUSE_BUTTON_LEFT = '<Button-1>'
MOUSE_BUTTON_RIGHT = '<Button-3>'
MOUSE_BUTTON_SCROLL_UP = '<Button-4>'
MOUSE_BUTTON_SCROLL_DOWN = '<Button-5>'
MOUSE_MOTION = '<Motion>'
MOUSE_MOTION_LEFT = '<B1-Motion>'
MOUSE_MOTION_RIGHT = '<B3-Motion>'
MOUSE_RELEASE_LEFT = '<ButtonRelease-1>'
MOUSE_RELEASE_RIGHT = '<ButtonRelease-3>'
MOUSE_ENTER_WIDGET = '<Enter>'
MOUSE_LEAVE_WIDGET = '<Leave>'
MOUSE_FOCUSIN_WIDGET = '<FocusIn>'
MOUSE_FOCUSOUT_WIDGET = '<FocusOut>'

RECONFIGURE = '<Configure>'

KEY_ESC = '<Escape>'
KEY_ENTER = '<Return>'
KEY_PAGEUP = '<Prior>'
KEY_PAGEDOWN = '<Next>'
KEY_LEFT = '<Left>'
KEY_RIGHT = '<Right>'
KEY_UP = '<Up>'
KEY_DOWN = '<Down>'